SELECT * FROM TAB;

DESC CENTER;
SELECT * FROM CENTER;

DESC MEMBER;
SELECT * FROM MEMBER;

DROP TABLE CENTER;
CREATE TABLE CENTER(
    CNAME VARCHAR2(300),
    FNAME VARCHAR2(300) NOT NULL,
    POSTCODE VARCHAR2(10) NOT NULL,
    DISTRICT VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(300) NOT NULL,
    CONTACT VARCHAR2(15)
 );   
ALTER TABLE CENTER ADD CONSTRAINT PK_CENTER_FAC_NAME PRIMARY KEY (CNAME, FNAME);

CREATE TABLE MEMBER(
    REGINUM VARCHAR(15),
    MNAME VARCHAR2(30) NOT NULL,
    CONTACT VARCHAR(15) NOT NULL,
    DISTRICT VARCHAR2(30) NOT NULL,
    VACTYPE VARCHAR2(30) NOT NULL,
    DATE_FIRST VARCHAR2(15) NOT NULL,
    DATE_SECOND VARCHAR2(15) NOT NULL,
    NOTIDATE VARCHAR2(15) NOT NULL
);
ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER_REGINUM PRIMARY KEY(REGINUM);


-- 레코드를 추가
-- INSERT INTO MEMBER VALUES('user01', 'password01', '홍길동', '010-1234-1111', 'user01@work.com', '2017.05.05', 'G', 75000, NULL);

-- UNIQUE 제약조건 추가
-- ALTER TABLE 테이블명 ADD CONSTRAINT UK_MEMBER_ UNIQUE (UNIQUE컬럼명);

-- 외래키 제약조건 추가 
-- ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_DISTRICT FOREIGN KEY(DISTRICT) REFERENCES CENTER(DISTRICT);

SELECT DISTINCT DISTRICT FROM CENTER;

DELETE FROM CENTER WHERE CNAME = '코로나19 서울특별시 강북구 예방접종센터' AND FNAME = '강북구 문화예술회관';
DELETE FROM CENTER;
ROLLBACK;

SELECT * FROM CENTER WHERE CNAME LIKE '%강남%' OR FNAME LIKE '%강남%' OR ADDRESS LIKE '%강남%';

select * from resource_limit where resource_name = 'processes';
alter system set processes=300 scopte=spfile;

SELECT * FROM MEMBER WHERE MNAME = '김현수' AND REGINUM = '970620-1234567';